services:
  app:
    build:
      args:
        user: dani
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kinerjaplus
    container_name: kinerjaplus-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kinerjaplus

  nginx:
    image: nginx:alpine
    container_name: kinerjaplus-nginx
    restart: unless-stopped
    ports:
      - 8123:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - kinerjaplus

  db:
    image: mysql:8.0
    container_name: kinerjaplus-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3307:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - kinerjaplus
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: kinerjaplus-phpmyadmin
    links:
      - db
    restart: unless-stopped
    ports:
      - 8124:80
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    networks:
      - kinerjaplus

networks:
  kinerjaplus:
    driver: bridge